/**
 * Mock data for frontend development when API is unavailable
 */

import { Product } from './api';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Extra Virgin Olive Oil - 250ml",
    slug: "extra-virgin-250ml",
    description: "Cold-pressed extra virgin olive oil in 250ml bottle",
    short_description: "Premium quality, early harvest",
    price: 24.99,
    discount_price: null,
    stock: 50,
    category: "Bottles",
    image_url: null,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Extra Virgin Olive Oil - 500ml",
    slug: "extra-virgin-500ml",
    description: "Cold-pressed extra virgin olive oil in 500ml bottle",
    short_description: "Best seller, family size",
    price: 44.99,
    discount_price: 39.99,
    stock: 100,
    category: "Bottles",
    image_url: null,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Extra Virgin Olive Oil - Tin Can 300ml",
    slug: "extra-virgin-tin-300ml",
    description: "Premium packaging in 300ml tin can",
    short_description: "Gift-worthy presentation",
    price: 34.99,
    discount_price: null,
    stock: 30,
    category: "Cans",
    image_url: null,
    is_active: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Extra Virgin Olive Oil - Tin Can 500ml",
    slug: "extra-virgin-tin-500ml",
    description: "Premium packaging in 500ml tin can",
    short_description: "Best value, premium package",
    price: 54.99,
    discount_price: null,
    stock: 25,
    category: "Cans",
    image_url: null,
    is_active: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Extra Virgin Olive Oil - Bulk 1L",
    slug: "extra-virgin-1l",
    description: "Bulk size for restaurants and families",
    short_description: "Bulk savings",
    price: 79.99,
    discount_price: null,
    stock: 15,
    category: "Bulk",
    image_url: null,
    is_active: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Extra Virgin Olive Oil - Gift Set",
    slug: "extra-virgin-gift-set",
    description: "Curated gift set with 250ml and 500ml bottles",
    short_description: "Perfect gift for olive oil lovers",
    price: 69.99,
    discount_price: null,
    stock: 20,
    category: "Gift Sets",
    image_url: null,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
