"""Add homepage_content table

Revision ID: 3d3329fcf7ee
Revises: b81db91380b6
Create Date: 2026-07-20 11:36:03.473419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3329fcf7ee'
down_revision: Union[str, None] = 'b81db91380b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('hero_brand_name', sa.String(length=255), nullable=True),
    sa.Column('hero_headline', sa.String(length=255), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.Column('hero_primary_cta_text', sa.String(length=255), nullable=True),
    sa.Column('hero_secondary_cta_text', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_content')
    # ### end Alembic commands ###
